CREATE TABLE IF NOT EXISTS tier_features (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tier VARCHAR(20) NOT NULL,
  feature_key VARCHAR(100) NOT NULL,
  limit_value INTEGER,
  value_description TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(tier, feature_key)
);

INSERT INTO tier_features (tier, feature_key, limit_value, value_description) VALUES
('free', 'weekly_briefs', NULL, 'Access to weekly briefs'),
('free', 'commands_per_week', 1, '1 command per week'),
('free', 'vault_access', NULL, 'Read-only access to 3 blueprints'),
('free', 'foundry_scorecard', NULL, 'Monthly rating'),
('free', 'cohort_dashboard', NULL, 'Anonymized metrics'),
('pro', 'daily_briefs', NULL, 'Daily weekday briefs'),
('pro', 'ai_advisor_sessions', 20, '20 AI Advisor sessions per month'),
('pro', 'playbook_access', NULL, 'Full playbook with 7 modules'),
('pro', 'vault_access', NULL, 'Full vault access, all blueprints'),
('pro', 'commands_per_week', NULL, 'Unlimited commands'),
('pro', 'creator_suite', NULL, '70/30 split on subscriber revenue'),
('pro', 'referral_earnings', NULL, '$5 per subscription'),
('pro', 'community_access', NULL, 'Slack + office hours'),
('pro', 'analytics', NULL, 'Read rate and engagement'),
('max', 'daily_briefs', NULL, 'Custom daily brief'),
('max', 'ai_advisor_sessions', NULL, 'Unlimited sessions'),
('max', 'playbook_access', NULL, 'Full playbook'),
('max', 'vault_access', NULL, 'Full vault'),
('max', 'commands_per_week', NULL, 'Unlimited commands'),
('max', 'creator_suite', NULL, '70/30 split + leaderboard featured'),
('max', 'referral_earnings', NULL, '$5 per subscription'),
('max', 'community_access', NULL, 'Slack + office hours'),
('max', '1on1_monthly', NULL, '30min monthly with exited founder'),
('max', 'code_review', NULL, 'CTO private code audit'),
('max', 'deal_flow_access', NULL, 'Companies raising, investments'),
('max', 'cofounder_matching', NULL, 'Algorithm-based co-founder discovery'),
('max', 'investor_intros', 3, '3 warm intros per year'),
('max', 'founder_events', NULL, 'Quarterly in-person masterminds'),
('max', 'team_seats', NULL, 'Add co-founders at +$50/seat'),
('incubator', 'everything_in_max', NULL, 'All Max tier features'),
('incubator', 'weekly_checkins', NULL, 'Founder + ops/product team'),
('incubator', 'architecture_audit', NULL, 'Full tech stack review'),
('incubator', 'first_revenue_sprint', NULL, '30-day path to $1k MRR'),
('incubator', 'fundraising_playbook', NULL, 'Pitch deck + VC intros'),
('incubator', 'exit_positioning', NULL, 'M&A strategy from day 1');
