import { Router, type IRouter } from "express";
import healthRouter from "./health";
import subscribersRouter from "./subscribers";
import analyticsRouter from "./analytics";
import confirmRouter from "./confirm";
import cronRouter from "./cron";
import earningsRouter from "./earnings";
import marketplaceRouter from "./marketplace-creator";
import creatorRouter from "./creator";
import teamSeatsRouter from "./team-seats";
import engineRouter from "./engine";
import paymentsRouter from "./payments";
import referralsRouter from "./referrals";
import incubatorRouter from "./incubator";
import scorecardRouter from "./scorecard";
import terminalRouter from "./terminal";
import wallsRouter from "./walls";
import vaultsRouter from "./vaults";
import contentRouter from "./content";
import briefsRouter from "./briefs";
import leadsRouter from "./leads";
import foundersRouter from "./founders";
import onboardingRouter from "./onboarding";
import journeyRouter from "./journey";
import weeklyCheckInsRouter from "./weekly-checkins";
import marketSizingRouter from "./market-sizing";
import competitiveAnalysisRouter from "./competitive-analysis";
import coFounderMatchingRouter from "./co-founder-matching";
import funnelRouter from "./funnel";
import ideaAgentRouter from "./idea-agent";
import userRouter from "./user";
import templatesRouter from "./templates";
import investorRouter from "./investor";

const router: IRouter = Router();

router.use(healthRouter);
router.use(subscribersRouter);
router.use(analyticsRouter);
router.use(confirmRouter);
router.use(cronRouter);
router.use(earningsRouter);
router.use(marketplaceRouter);
router.use(creatorRouter);
router.use(teamSeatsRouter);
router.use(engineRouter);
router.use(paymentsRouter);
router.use(referralsRouter);
router.use(incubatorRouter);
router.use(scorecardRouter);
router.use(terminalRouter);
router.use(wallsRouter);
router.use('/vaults', vaultsRouter);
router.use(contentRouter);
router.use(briefsRouter);
router.use(leadsRouter);
router.use(foundersRouter);
router.use('/onboarding', onboardingRouter);
router.use('/journey', journeyRouter);
router.use('/weekly-checkins', weeklyCheckInsRouter);
router.use('/market-sizing', marketSizingRouter);
router.use('/competitive-analysis', competitiveAnalysisRouter);
router.use('/co-founder-matching', coFounderMatchingRouter);
router.use('/api/upgrades', funnelRouter);
router.use('/api/idea-agent', ideaAgentRouter);
router.use('/api/user', userRouter);
router.use('/api/templates', templatesRouter);
router.use('/api/investor', investorRouter);

export default router;
