import { Router, type IRouter } from "express";
import healthRouter from "./health";
import subscribersRouter from "./subscribers";
import analyticsRouter from "./analytics";
import confirmRouter from "./confirm";
import cronRouter from "./cron";
import earningsRouter from "./earnings";
import marketplaceRouter from "./marketplace-creator";
import creatorRouter from "./creator";
import teamSeatsRouter from "./team-seats";
import engineRouter from "./engine";
import paymentsRouter from "./payments";
import referralsRouter from "./referrals";
import incubatorRouter from "./incubator";
import scorecardRouter from "./scorecard";
import terminalRouter from "./terminal";
import wallsRouter from "./walls";
import vaultsRouter from "./vaults";
import contentRouter from "./content";
import briefsRouter from "./briefs";
import leadsRouter from "./leads";
import foundersRouter from "./founders";

const router: IRouter = Router();

router.use(healthRouter);
router.use(subscribersRouter);
router.use(analyticsRouter);
router.use(confirmRouter);
router.use(cronRouter);
router.use(earningsRouter);
router.use(marketplaceRouter);
router.use(creatorRouter);
router.use(teamSeatsRouter);
router.use(engineRouter);
router.use(paymentsRouter);
router.use(referralsRouter);
router.use(incubatorRouter);
router.use(scorecardRouter);
router.use(terminalRouter);
router.use(wallsRouter);
router.use(vaultsRouter);
router.use(contentRouter);
router.use(briefsRouter);
router.use(leadsRouter);
router.use(foundersRouter);

export default router;
